/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/a5b7694d-8b4e-47b3-85a6-4095fa2dffa9 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  String msg;
  int DIST;
  bool chgDIR;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <Servo.h>

#define trigger_pin 5
#define Echo_pin 18

int distance;
long duration;
const int obstacle_distance = 35;

const int Servo_wing = 13;
Servo Wing;
int pos = 0;

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  pinMode(trigger_pin, OUTPUT);
  pinMode(Echo_pin, INPUT);
  Wing.attach(Servo_wing);
  
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  digitalWrite(trigger_pin, LOW);
  delayMicroseconds(2);

  digitalWrite(trigger_pin, HIGH);
  delayMicroseconds(10);
  digitalWrite(trigger_pin, LOW);

  duration = pulseIn(Echo_pin, HIGH);
  distance = duration * 0.034 / 2;
  DIST = distance;
  
  if (distance < obstacle_distance) {
    chgDIR = true;
    msg = "Obstacle detected, Changing Direction";
    for (pos = 0; pos <= 90; pos += 1) {
      Wing.write(pos);
      delay(10);
    }
    for (pos = 90; pos >= 0; pos -= 1) {
      Wing.write(pos);
      delay(10);
    }
    Serial.println("Obstacle detected, Changing Direction");
  } else {
    chgDIR = false;
    msg = "No Obstacle";
    Wing.write(pos);
    Serial.println("No Obstacles");
  }

  Serial.print("Distance: ");
  Serial.print(distance);
  Serial.println(" cm");
  delay(100);  
  
}


/*
  Since DIST is READ_WRITE variable, onDISTChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onDISTChange()  {
  // Add your code here to act upon DIST change
}

/*
  Since ChgDIR is READ_WRITE variable, onChgDIRChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onChgDIRChange()  {
  // Add your code here to act upon ChgDIR change
}



