/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/dfecc9e9-571b-4761-b672-a38388585a85 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool dirchng;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
int MtrInpt1 = 27;
int MtrInpt2 = 26;
int enablePin = 14;

// Setting PWM properties
const int freq = 30000;
const int pwmChannel = 0;
const int resolution = 8;
int dutyCycle = 150;

void setup() {
  pinMode(MtrInpt1, OUTPUT);
  pinMode(MtrInpt2, OUTPUT);
  pinMode(enablePin, OUTPUT);

  // configure LED PWM functionalitites
  ledcSetup(pwmChannel, freq, resolution);

  // attach the channel to the GPIO to be controlled
  ledcAttachPin(enablePin, pwmChannel);
  
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  if(dirchng == false){
    digitalWrite(MtrInpt1, LOW);
    digitalWrite(MtrInpt2, LOW);
  } 
  else if(dirchng == true){
    digitalWrite(MtrInpt1, HIGH);
    digitalWrite(MtrInpt2, LOW);
    ledcWrite(pwmChannel, dutyCycle);
    delay(1100);
  
    digitalWrite(MtrInpt1, LOW);
    digitalWrite(MtrInpt2, LOW);
    delay(1000);
  }
  
}


/*
  Since Dirchng is READ_WRITE variable, onDirchngChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onDirchngChange()  {
  // Add your code here to act upon Dirchng change
}


